---
# Root password
bootstrap__root_pass: '{{lookup("bitwarden", "root-pass")}}'
# Consul
bootstrap__consul_encryption_key:   '{{lookup("bitwarden", "consul/cluster", field="encryption-key")}}'
bootstarp__consul_agent_acl_token:  '{{lookup("bitwarden", "consul/acl-tokens", field="agent-default")}}'
bootstrap__consul_certs_ca_crt:     '{{lookup("bitwarden", "consul/certs",      file="ca.pem")}}'
bootstrap__consul_certs_client_crt: '{{lookup("bitwarden", "consul/certs",      file="client.pem")}}'
bootstrap__consul_certs_client_key: '{{lookup("bitwarden", "consul/certs",      file="client-key.pem")}}'
# SSHGuard
bootstrap__sshguard_whitelist_extra: ['{{lookup("bitwarden", "sshguard/whitelist", field="jakubgs-home")}}']
# Wireguard
wireguard_consul_acl_token: '{{lookup("bitwarden", "consul/acl-tokens", field="wireguard")}}'

# Volume of Trace level logs is too high and fills up ES cluster.
bootstrap__rsyslog_filter_rules: ['TRC']

# Docker registry
bootstrap__docker_registries:
  - url:      'https://harbor.status.im'
    username: 'robot$wakuorg+infra-status'
    password: '{{ lookup("bitwarden", "harbor-robot", field="robot$wakuorg+infra-status") }}'

# Vault certificate
bootstrap__vault_ca_cert:           '{{ lookup(passwordstore, services/vault/certs/root-ca/cert returnall=true)}}'
bootstrap__vault_client_cert:       '{{ lookup(passwordstore, services/vault/certs/client-host/cert returnall=true)}}'
bootstrap__vault_client_key:        '{{ lookup(passwordstore, services/vault/certs/client-host/privkey returnall=true)}}'
