---
- name: Verify Ansible versions
  hosts: all
  tags: always
  become: false
  run_once: true
  gather_facts: false
  tasks:
    - local_action: command ./roles.py --check
      changed_when: false

- name: Configure Waku Storage DB Nodes
  serial: '{{ serial|default(1) }}'
  hosts: store-db
  roles:
    - { role: infra-role-open-ports,   tags: open-ports  }
    - { role: infra-role-swap-file,    tags: swap-file   }
    - { role: infra-role-postgres-ha,  tags: postgres-ha }
    - { role: infra-role-wazuh-agent,  tags: wazuh-agent }

- name: Configure Waku Bootstrap and Storage Nodes
  serial: '{{ serial|default(1) }}'
  hosts:
    - boot
    - store
  roles:
    - { role: infra-role-open-ports,     tags: open-ports                                   }
    - { role: infra-role-swap-file,      tags: swap-file                                    }
    - { role: infra-role-certbot,        tags: certbot                                      }
    - { role: infra-role-nim-waku,       tags: nim-waku                                     }
    - { role: infra-role-nim-waku-sonda, tags: nim-waku-sonda, when: nim_waku_sonda_enabled }
    - { role: infra-role-nginx,          tags: nginx                                        }
    - { role: infra-role-wazuh-agent,    tags: wazuh-agent                                  }
