- name: infra-role-bootstrap-linux
  src: git@github.com:status-im/infra-role-bootstrap-linux.git

- name: infra-role-wireguard
  src: git@github.com:status-im/infra-role-wireguard.git

- name: infra-role-open-ports
  src: git@github.com:status-im/infra-role-open-ports.git

- name: infra-role-swap-file
  src: git@github.com:status-im/infra-role-swap-file.git

- name: infra-role-consul-service
  src: git@github.com:status-im/infra-role-consul-service.git

- name: infra-role-systemd-timer
  src: git@github.com:status-im/infra-role-systemd-timer.git

- name: infra-role-nim-waku
  src: git@github.com:status-im/infra-role-nim-waku.git
  version: ef2fb8f244c6256561d00571bb620847db4c4022

- name: infra-role-certbot
  src: git@github.com:status-im/infra-role-certbot.git
  version: 8b5f4ed137e399a33c10b7ffbeaacb6e0c52fcb1

- name: infra-role-postgres-ha
  src: git@github.com:status-im/infra-role-postgres-ha.git
  version: a9408d3fac887343039c867fad3740bd5b3fcce6

- name: infra-role-nim-waku-sonda
  src: git@github.com:status-im/infra-role-nim-waku-sonda.git
  version: 62f0e89c07054689cba9ac6bd49a1a680fc8a9d1

- name: infra-role-wazuh-agent
  src: git@github.com:status-im/infra-role-wazuh-agent.git
  version: e521f94f2dee59ce67f383b97ce1b3a956144afe
